### ISSUE TITLE
Crash at launch

### ISSUE THREAD

**Issue by copytco** [SaiyansKing/GD3D11#38] opened 2021-12-27 09:17 UTC
Hi, I am having access denied error. Have not found it elesewhere, so posting issue here. Happens just after launching executable.

---------------------------
Gothic GD3D11
---------------------------
GD3D11 Renderer couldn't be loaded.
Access Denied(0x3e6).
---------------------------
OK   
---------------------------

After the error, exe is crashing.

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	Gothic2.exe
  Application Version:	2.6.0.0
  Application Timestamp:	3f966d87
  Fault Module Name:	nvapi.dll
  Fault Module Version:	23.21.13.9135
  Fault Module Timestamp:	5ab5810a
  Exception Code:	c0000005
  Exception Offset:	00346230
  OS Version:	6.1.7601.2.1.0.768.3
  Locale ID:	1045
  Additional Information 1:	101e
  Additional Information 2:	101ece011e39c7777753d35c68914446
  Additional Information 3:	900e
  Additional Information 4:	900e6e6aa46c0ecd62a8ca0c567d35f0

**Comment by SaiyansKing** [comment] 2021-12-27 16:05
Hi,
duplicate of https://github.com/SaiyansKing/GD3D11/issues/21, it seems some component of Windows 7 blocks GD3D11 from being loaded. I can't do anything more than recommending disabling any type of antivirus and reinstalling vc_redist(it might be possible that you have only x64 version installed which is wrong because in this case you need x86).

**Comment by copytco** [comment] 2021-12-27 20:07
Solved it by downgrading nVidia drivers to 320.

**Comment by SaiyansKing** [comment] 2021-12-27 21:17
> I have Vista. Solved it by downgrading nVidia drivers to 320.

Then I'm happy it worked, just so you know GD3D11 renderer doesn't work on Vista because it need minimum DXGI 1.2 and Windows Vista didn't get platform update. Also `OS Version: 6.1.7601.2.1.0.768.3` means that you're using Windows 7 with Service Pack 1(minimum supported OS by this GD3D11 renderer).

**Closed** 2021-12-27 22:19 UTC
